services:
  localstack:
    container_name: localstack_statusListMock
    image: localstack/localstack:latest
    ports:
      - "4562:4566"
    environment:
      - SERVICES=kms,s3,lambda,apigateway
      - AWS_ACCESS_KEY_ID=na
      - AWS_SECRET_ACCESS_KEY=na
      - AWS_DEFAULT_REGION=eu-west-2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker-reuse
    volumes:
      - './localstack/provision.sh:/etc/localstack/init/ready.d/provision.sh'
      - './dist:/tmp/lambda-code'
      - '/var/run/docker.sock:/var/run/docker.sock'